Added Dark Matter Labs
life-itself/ecosystem pull request #231
Opened 2024-02-28 14:43 UTC by elisapaka

2024-02-28 19:14 UTC, catherinet1 requested changes
main thing is links to the source of direct quotations

2024-02-28 19:14 UTC, catherinet1 commented on content/tbd/Dark Matter Labs.md
> +
Hi @elisapaka looks good -- only thing is to add links when quoting directly from website

2024-02-28 19:14 UTC, catherinet1 commented on content/tbd/Dark Matter Labs.md
> +> We’re establishing toolkits and blueprints, pilots, and case studies, supporting communities and institutions with applications, digital products and civic technologies that challenge established t
this stuff i'd probably put above in the about/description section, as opposed to theory of change section, as it seems to me more about their activities/what they're doing as opposed to their theory or strategy or underlying principles of change.

2024-03-07 11:09 UTC, rufuspollock commented
@elisapaka does this replace this previous PR https://github.com/life-itself/ecosystem/pull/209 - if so let's close that old one with note that replaced by this.

2024-03-12 14:03 UTC, merged